In [16]:
import pandas as pd

In [17]:
dataset=pd.read_csv("insurance_pre.csv")

In [18]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [19]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)

In [20]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [21]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [24]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()
regressor=regressor.fit(X_train,y_train)

In [25]:
y_pred=regressor.predict(X_test)

In [26]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [27]:
r_score

0.692020379676229

In [31]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(criterion="squared_error", splitter="best")
regressor=regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.7036256780594246

In [32]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(criterion="squared_error", splitter="random")
regressor=regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.7211773811619888

In [34]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(criterion="friedman_mse", splitter="best")
regressor=regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.6878798495376094